string(TOUPPER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_UPPER)
cmake_print_variables(CMAKE_BUILD_TYPE)
cmake_print_variables(CMAKE_C_FLAGS)
cmake_print_variables("CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}")
cmake_print_variables(CMAKE_CXX_FLAGS)
cmake_print_variables("CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}")
cmake_print_variables(CMAKE_ASM_FLAGS)
cmake_print_variables("CMAKE_ASM_FLAGS_${CMAKE_BUILD_TYPE_UPPER}")
cmake_print_variables(CMAKE_EXE_LINKER_FLAGS)
cmake_print_variables("CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}")
